name: Submit your banking app report
description: Report a banking app's compatibility on GrapheneOS
title: "[Replace this with the name of your banking app]"
labels: ["app report"]
body:
  - type: markdown
    attributes:
      value: |
        If you haven't already, please view the official [banking apps usage guide](https://grapheneos.org/usage#banking-apps). 
        
        Experiencing issues with your app, refer to the [possible workaround solutions on our forum](https://discuss.grapheneos.org/d/8330-app-compatibility-with-grapheneos).
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists to avoid creating duplicates.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    id: version
    attributes:
      label: App name
      description: What is the banking app called?
      placeholder: BMO Mobile Banking
    validations:
      required: true
  - type: input
    id: app_link
    attributes:
      label: Link to app
      description: Paste the download link (Play Store preferably) or tell us where to get the app if possible
      placeholder: https://play.google.com/store/apps/details?id=com.bmo.mobile
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: App version
      description: |
        What version of the app did you test it with?
        
        `Settings` → `Apps` → `All apps` → `<app_name>` → `Version`       
      placeholder: v1.3.3.7
    validations:
      required: true
  - type: input
    id: country
    attributes:
      label: Country of the app
      description: Specify what country the app is for (it is assumed you're using it in the same country here)
      placeholder: Canada
    validations:
      required: true
  - type: input
    id: build_number
    attributes:
      label: Build Number
      description: |
        What version of GrapheneOS are you currently using? 
        
        `Settings` → `About phone` → `Build number`
      placeholder: SP2A.220405.003.2022040400
    validations:
      required: true
  - type: dropdown
    id: selectdevice
    attributes:
      label: Device list
      description: Which Pixel(s) have you tested this with? (Select one or multiple)
      multiple: true
      options:
        - Pixel 8 Pro
        - Pixel 8
        - Pixel Fold
        - Pixel Tablet
        - Pixel 7a
        - Pixel 7 Pro
        - Pixel 7
        - Pixel 6a
        - Pixel 6 Pro
        - Pixel 6
        - Pixel 5a
        - Pixel 5 (EOL)
        - Pixel 4a (5G)
        - Pixel 4a (EOL/ESR)
        - Pixel 4 XL (EOL/ESR)
        - Pixel 4 (EOL/ESR)
        - Pixel 3a XL (obsolete)
        - Pixel 3a (obsolete)
        - Pixel 3 XL (obsolete)
        - Pixel 3 (obsolete)
    validations:
        required: true
  - type: dropdown
    id: profiles
    attributes:
      label: Profile app tested in
      description: Which user profile was this test on? (Select one or multiple)
      multiple: true
      options:
        - Owner profile
        - Secondary profile(s)
        - Work profile (Add details in extra notes below, i.e., device manager app name)
    validations:
        required: true
  - type: dropdown
    id: googleplay
    attributes:
      label: Google Play installed
      description: Do you have Google Play installed in the profile you tested in?
      multiple: false
      options:
        - Not Installed
        - Installed
    validations:
        required: true
  - type: checkboxes
    attributes:
      label: Google Play services Network permission revoked?
      description: If you have Google Play installed, was the Network permission for Google Play services revoked?
      options:
        - label: Revoked
        - label: Not revoked
        - label: I did not have Google Play services installed
  - type: checkboxes
    attributes:
      label: Native code debugging
      description: |
        Was [native code debugging](https://grapheneos.org/usage#banking-apps) enabled or disabled during the testing? 
        
        `Settings` → `Security` → `Enable native code debugging`
      options:
        - label: Allowed
        - label: Blocked
  - type: checkboxes
    attributes:
      label: Exploit protection compatibility mode
      description: |
        Was per-app [exploit protection compatibility mode](https://grapheneos.org/usage#bugs-uncovered-by-security-features) enabled or disabled during the testing?
        
        `Settings` → `Apps` → `App` → `Advanced`
      options:
        - label: Enabled
        - label: Disabled
  - type: checkboxes
    attributes:
      label: Stock OS compatibility
      description: Does this app work on stock OS?
      options:
        - label: Works
        - label: Does not work
        - label: Not tested
  - type: checkboxes
    attributes:
      label: NFC payments
      description: Does this app allow NFC payments?
      options:
        - label: Works
        - label: Works but requires another service
        - label: Does not work
        - label: N/A (Not supported by app)
        - label: Not tested
  - type: textarea
    id: description
    attributes:
      label: Description of the app's functionality
      description: |
        What happens when you use the app? What tasks do work and don't work? What is the expected outcome of each thing you do? Did you test any other configurations and setups? Please mention all the steps to reproduce any issues. Do not leave out any information.

        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
  - type: textarea
    id: extra_notes
    attributes:
      label: Are there any extra notes you think users should know about?
      description: |
        Did you do any workarounds other users should know that aren't listed here?

        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: textarea
    id: adb_logs
    attributes:
      label: ADB logcat of the app if necessary
      description: |
        If you have any logs that come up that the app is creating relevant to anything mentioned like app crashes, SafetyNet, etc, please send a GitHub Gist of them. Do not send a bug report ZIP to us. They may expose sensitive information. If you wish to send a bug report ZIP, please do so directly to a GrapheneOS project member or developer.

        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
      render: systemverilog
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this report.
