name: Banking app report
description: Report a banking app's compatibility on GrapheneOS
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report! Please remember this is for GrapheneOS only.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists to avoid creating duplicates.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    id: version
    attributes:
      label: App name
      description: What is the banking app called?
      placeholder: 
    validations:
      required: true
  - type: input
    id: app_link
    attributes:
      label: Link to app
      description: Paste the download link (Play Store preferably) or tell us where to get the app if possible
      placeholder: 
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: App version
      description: What version of the app did you test it with? (Settings -> Apps -> app name -> Version at the bottom)
      placeholder: v1.3.3.7
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Device
      description: Which Pixel(s) have you tested this with?
      options:
        - label: Pixel 6 Pro
        - label: Pixel 6
        - label: Pixel 5a
        - label: Pixel 5
        - label: Pixel 4a (5G)
        - label: Pixel 4a
        - label: Pixel 3a XL
        - label: Pixel 3a
        - label: Pixel 3 XL
        - label: Pixel 3
  - type: checkboxes
    attributes:
      label: Google Play installed
      description: Do you have Google Play installed in the profile you tested in?
      options:
        - label: Installed
        - label: Not installed
  - type: checkboxes
    attributes:
      label: SafetyNet Enforcement
      description: Does this app enforce SafetyNet?
      options:
        - label: Enforced
        - label: Not enforced
  - type: checkboxes
    attributes:
      label: Native code debugging
      description: Was native code debugging enabled or disabled during the testing? (Settings -> Security -> Enable native code debugging)
      options:
        - label: Enabled
        - label: Disabled
  - type: checkboxes
    attributes:
      label: Stock OS compatibility
      description: Does this app work on stock OS?
      options:
        - label: Works
        - label: Does not work
        - label: Not tested
  - type: checkboxes
    attributes:
      label: Profile app tested in
      description: Which user profile was this tested on?
      options:
        - label: Main user profile
        - label: Secondary user profile
        - label: I used a work profile device manager app (Please mention more details about it down below like the app)
  - type: textarea
    id: description
    attributes:
      label: Description of the app's functionality
      description: |
        What happens when you use the app? What tasks do work and don't work? What is the expected outcome of each thing you do? Did you test any other configurations and setups? Please mention all the steps to reproduce any issues. Do not leave out any information.

        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
  - type: textarea
    id: adb_logs
    attributes:
      label: ADB logcat of the app if necessary
      description: |
        If you have any logs that come up that the app is creating relevant to anything mentioned like app crashes, SafetyNet, etc, please send a GitHub Gist of them. Do not send a bug report ZIP to us. They may expose sensitive information. If you wish to send a bug report ZIP, please do so directly to a GrapheneOS project member or developer.

        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: textarea
    id: extra_notes
    attributes:
      label: Is there any extra notes you think users should know about?
      description: |
        Did you do any workarounds other users should know that aren't listed here?

        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
